### ISSUE TITLE
源码无法正常跑起来

### ISSUE THREAD

**Issue by freekingg** [klren0312/house365Spider#16]
导入应用报错。。。。
点击开始测试报错。。。

作者麻烦修复下哦

**Comment by klren0312** [comment]
可以先切master分支试试, dev分支还在搞...

**Comment by freekingg** [comment]
> 可以先切master分支试试, dev分支还在搞...

恩，应该是版本兼容问题，现在版本升级后，puppeteer在electron中有兼容问题，需要处理

**Comment by klren0312** [comment]
> > 可以先切master分支试试, dev分支还在搞...
> 
> 恩，应该是版本兼容问题，现在版本升级后，puppeteer在electron中有兼容问题，需要处理

嗯嗯 有时间大整一下

**Comment by freekingg** [comment]
> > > 可以先切master分支试试, dev分支还在搞...
> > 
> > 
> > 恩，应该是版本兼容问题，现在版本升级后，puppeteer在electron中有兼容问题，需要处理
> 
> 嗯嗯 有时间大整一下

![image](https://user-images.githubusercontent.com/23447622/126271275-c878ce4d-e4bb-45ee-9352-81158120f437.png)
我这样解决了

**Comment by klren0312** [comment]
那应该跟这块一样
https://github.com/klren0312/ZSpider/blob/dev/vue.config.js#L8

**Comment by klren0312** [comment]
导入应用错误已修改, 换成了`showOpenDialogSync`就可以了
开始测试错误已修改, `puppeteer-core`得放在外部扩展
