### ISSUE TITLE
错误提示超时 ERR_SOCKET_TIMEOUT

### ISSUE THREAD

**Issue by ityz-com** [klren0312/house365Spider#28]
![image](https://user-images.githubusercontent.com/20999404/179712726-e7b2a25b-ce42-4272-af10-12db0fc69f64.png)

有在科学上网的条件测试过也是一样

**Comment by klren0312** [comment]
![图片](https://user-images.xmubusercontent.com/10903843/179723856-ca5030ce-5be5-4ed5-a2b8-a82a19e5cdd1.png)

现拉代码 没有代理, 安装可以...  要不你试试吧lock文件和.npmrc文件全删了,

**Comment by klren0312** [comment]
已更新dev分支 请尝试
