### ISSUE TITLE
尝试很多方法项目跑不起来

### ISSUE THREAD

**Issue by muyilongh** [klren0312/house365Spider#35]
能详细说明一下node版本 npm版本 或者其他没卸载json里的插件的特殊要求吗

**Comment by klren0312** [comment]
我重新拉下来跑下看看

**Comment by muyilongh** [comment]
我的name.5.5 node16.3.0
我现在打不开github只能邮箱回了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月20日(周二) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [klren0312/ZSpider] 尝试很多方法项目跑不起来 (Issue #35)

**Comment by muyilongh** [comment]
ERROR  ValidationError: Progress Plugin Invalid Options
        
        options should NOT have additional properties
        options should NOT have additional properties
        options should NOT have additional properties
        options should pass "instanceof" keyword validation
        options should match exactly one schema in oneOf
        
ValidationError: Progress Plugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

百度后没什么有用的方法

**Comment by muyilongh** [comment]
npm 8.5.5   node16.3.0

**Comment by muyilongh** [comment]
我是mac环境

**Comment by klren0312** [comment]
方法肯定是没有 依赖版本乱了, 我慢慢改
完整功能你可以切分支到master,
https://github.com/klren0312/ZSpider/tree/master

**Comment by muyilongh** [comment]
你那儿有能给发一个node_modules 压缩包吗，我所有分支都试了问题都一样，各种依赖报错，百度谷歌都解决不了。

**Comment by muyilongh** [comment]
麻烦你有空的时候把node_modules 压缩发我一份。我百度谷歌试了所有分支报各种错误解决不了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [klren0312/ZSpider] 尝试很多方法项目跑不起来 (Issue #35)





 
方法肯定是没有 依赖版本乱了
 完整功能你可以切分支到master,
 https://github.com/klren0312/ZSpider/tree/master

**Comment by klren0312** [comment]
问题已修改, 重新拉dev分支试试
