### ISSUE TITLE
项目我跑起来了发现几个bug我本地修复能跑了代码我提交吗

### ISSUE THREAD

**Issue by muyilongh** [klren0312/house365Spider#36]
我不清楚是我本地环境问题还是mysql版本问题，发布中的测试连接按钮，点击后会报错误，我换了种写法就可以发布了。
顺便问一下1200端口那个ws协议有什么用怎么启动websocket服务器呢。

**Comment by klren0312** [comment]
可以提交

ws服务在这 https://github.com/klren0312/ZSpider/blob/dev/server/index.js
当时主要用来统计设备在线的

**Comment by muyilongh** [comment]
怎么运行ws呢

**Comment by klren0312** [comment]
> 怎么运行ws呢

```
cd /server
npm install
# 先配置`index.js里的数据库`, 然后运行
node index.js
```

运行后 在https://github.com/klren0312/ZSpider/blob/dev/src/store/index.js 文件中修改api地址和ws地址
