### ISSUE TITLE
我没权限提交啊

### ISSUE THREAD

**Issue by muyilongh** [klren0312/house365Spider#37]
<img width="972" alt="WeChatb7fbef7e6b4e6eee5a72da4e1e0c1fe4" src="https://user-images.githubusercontent.com/960354/193183516-cd440266-7936-46f5-976e-eb3b5ae84fd5.png">
我去掉了scket 修复数据库连接测试 增加可视化获取选择器（功能实现了由于对vue不熟有一些bug，不知道你对可视化选择器感兴趣不，在dev分支改了不少能提交吗？）
![Uploading image.png…]()

**Comment by klren0312** [comment]
欢迎 可以提个pr看看

先fork这个仓库
然后提交你的代码到你fork的仓库
之后页面会有pr的按钮

**Comment by muyilongh** [comment]
pr是啥，我第一次下载别人项目不太会整



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月30日(周五) 中午1:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [klren0312/ZSpider] 我没权限提交啊 (Issue #37)

**Comment by klren0312** [comment]
> pr是啥，我第一次下载别人项目不太会整
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月30日(周五) 中午1:38 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [klren0312/ZSpider] 我没权限提交啊 (Issue #37)

https://juejin.cn/post/6844903821521469448
